### ISSUE TITLE
Syntax Error: invalid Syntax Line 278

### ISSUE THREAD

**Issue by schlitzer81** [JonnoFTW/img_term#2]
Hi there, I got this error when calling

img_term -img test.jpg

**Error**
Traceback (most recent call last):
  File "/usr/local/bin/img_term", line 7, in <module>
    from img_term.img_term import main
  File "/usr/local/lib/python2.7/dist-packages/img_term/img_term.py", line 278
    print("\x1b[;H", img_24bit(plasma_gen(), rows, columns), '\x1B[0m', sep='')
                                                                           ^
SyntaxError: invalid syntax

**Comment by JonnoFTW** [comment]
Hi,

You need to install/run with python3

Use `pip3 install img_term` and try again.

**Comment by schlitzer81** [comment]
Thx a lot. Works like a charm now.
